<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JZVerse.MicroHuaxia.Gateway.AspNetCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Abstractions\JZVerse.MicroHuaxia.Gateway.Abstractions.csproj" />
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Core\JZVerse.MicroHuaxia.Gateway.Core.csproj" />
  </ItemGroup>

</Project>
