<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>JZVerse.Business.Tests.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.6.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="FluentAssertions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Business\JZVerse.Business.Blog\JZVerse.Business.Blog.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Business\JZVerse.Business.Project\JZVerse.Business.Project.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Business\JZVerse.Business.Academy\JZVerse.Business.Academy.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Business\JZVerse.Business.Dashboard\JZVerse.Business.Dashboard.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Central\JZVerse.Business.Central.User\JZVerse.Business.Central.User.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Central\JZVerse.Business.Central.File\JZVerse.Business.Central.File.csproj" />
    <ProjectReference Include="..\..\..\src\JZVerse.Business\Central\JZVerse.Business.Central.Security\JZVerse.Business.Central.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Moq" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
