<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JZVerse.MicroHuaxia.ServiceDiscovery.AspNetCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JZVerse.MicroHuaxia.ServiceDiscovery.Client\JZVerse.MicroHuaxia.ServiceDiscovery.Client.csproj" />
    <ProjectReference Include="..\..\Security\JZVerse.MicroHuaxia.Security.Abstractions\JZVerse.MicroHuaxia.Security.Abstractions.csproj" />
    <ProjectReference Include="..\..\Security\JZVerse.MicroHuaxia.Security.Core\JZVerse.MicroHuaxia.Security.Core.csproj" />
    <ProjectReference Include="..\..\Security\JZVerse.MicroHuaxia.Security.AspNetCore\JZVerse.MicroHuaxia.Security.AspNetCore.csproj" />
  </ItemGroup>

</Project>
