<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>JZVerse.Business.Central.File</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
        <!-- MicroHuaxia 框架 -->
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\ServiceDiscovery\JZVerse.MicroHuaxia.ServiceDiscovery.AspNetCore\JZVerse.MicroHuaxia.ServiceDiscovery.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\ConfigCenter\JZVerse.MicroHuaxia.ConfigCenter.AspNetCore\JZVerse.MicroHuaxia.ConfigCenter.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\ServiceCommunication\JZVerse.MicroHuaxia.ServiceCommunication.AspNetCore\JZVerse.MicroHuaxia.ServiceCommunication.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\MessageQueue\JZVerse.MicroHuaxia.MessageQueue.Client\JZVerse.MicroHuaxia.MessageQueue.Client.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\Saga\JZVerse.MicroHuaxia.Saga.AspNetCore\JZVerse.MicroHuaxia.Saga.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\Observability\JZVerse.MicroHuaxia.Observability.AspNetCore\JZVerse.MicroHuaxia.Observability.AspNetCore.csproj" />
        
        <!-- 业务基础设施 -->
        <ProjectReference Include="..\..\JZVerse.Business.Infrastructure\JZVerse.Business.Infrastructure.csproj" />
        
        <!-- 数据访问 -->
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\DataAccess\JZVerse.MicroHuaxia.DataAccess.PostgreSql\JZVerse.MicroHuaxia.DataAccess.PostgreSql.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\DataAccess\JZVerse.MicroHuaxia.DataAccess.Caching.Dapper\JZVerse.MicroHuaxia.DataAccess.Caching.Dapper.csproj" />
    </ItemGroup>

</Project>
