<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>JZVerse.Business.Academy</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\JZVerse.Business.Infrastructure\JZVerse.Business.Infrastructure.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\DataAccess\JZVerse.MicroHuaxia.DataAccess.PostgreSql\JZVerse.MicroHuaxia.DataAccess.PostgreSql.csproj" />
        <ProjectReference Include="..\..\..\JZVerse.MicroHuaxia\DataAccess\JZVerse.MicroHuaxia.DataAccess.Caching.Dapper\JZVerse.MicroHuaxia.DataAccess.Caching.Dapper.csproj" />
    </ItemGroup>

</Project>
