<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.1.0" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0-beta.98" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.2.0" />

        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.1.0"/>
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.1.0"/>
        <PackageReference Include="Microsoft.Garnet" Version="2.0.0-beta.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.15.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0"/>
        <PackageReference Include="Quartz.AspNetCore" Version="3.15.1" />
        <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.15.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Map" Version="2.0.0" />
    </ItemGroup>

</Project>
