<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JZVerse.MicroHuaxia.Saga.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-rc.2.25502.107" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Saga.Core\JZVerse.MicroHuaxia.Saga.Core.csproj" />
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Saga.AspNetCore\JZVerse.MicroHuaxia.Saga.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ServiceDiscovery\JZVerse.MicroHuaxia.ServiceDiscovery.AspNetCore\JZVerse.MicroHuaxia.ServiceDiscovery.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ConfigCenter\JZVerse.MicroHuaxia.ConfigCenter.AspNetCore\JZVerse.MicroHuaxia.ConfigCenter.AspNetCore.csproj" />
    <ProjectReference Include="..\..\ServiceCommunication\JZVerse.MicroHuaxia.ServiceCommunication.AspNetCore\JZVerse.MicroHuaxia.ServiceCommunication.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Observability\JZVerse.MicroHuaxia.Observability.AspNetCore\JZVerse.MicroHuaxia.Observability.AspNetCore.csproj" />
  </ItemGroup>

</Project>
