<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>JZVerse.MicroHuaxia.Gateway.Http</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Abstractions\JZVerse.MicroHuaxia.Gateway.Abstractions.csproj" />
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Core\JZVerse.MicroHuaxia.Gateway.Core.csproj" />
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Resilience\JZVerse.MicroHuaxia.Gateway.Resilience.csproj" />
    <ProjectReference Include="..\JZVerse.MicroHuaxia.Gateway.Tracing\JZVerse.MicroHuaxia.Gateway.Tracing.csproj" />
    <ProjectReference Include="..\..\ServiceDiscovery\JZVerse.MicroHuaxia.ServiceDiscovery.Abstractions\JZVerse.MicroHuaxia.ServiceDiscovery.Abstractions.csproj" />
    <ProjectReference Include="..\..\ServiceCommunication\JZVerse.MicroHuaxia.ServiceCommunication.Abstractions\JZVerse.MicroHuaxia.ServiceCommunication.Abstractions.csproj" />
    <ProjectReference Include="..\..\ServiceCommunication\JZVerse.MicroHuaxia.ServiceCommunication.Core\JZVerse.MicroHuaxia.ServiceCommunication.Core.csproj" />
  </ItemGroup>

</Project>
